### ISSUE TITLE
Too generic exception in gRPC implementation

### ISSUE THREAD

**Issue by milossamek** [FgForrest/evitaDB#113]
Hello,

in current implementation of gRPC, it's not possible to identify the root cause of problem when exception is thrown.

Can you please expand the error conditions so that I can identify the problem?

Cheers

Stack:

````
io.grpc.StatusRuntimeException: INTERNAL: 
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271) ~[grpc_workaround_build-0.6-SNAPSHOT.jar:?]
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252) ~[grpc_workaround_build-0.6-SNAPSHOT.jar:?]
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165) ~[grpc_workaround_build-0.6-SNAPSHOT.jar:?]
	at io.evitadb.externalApi.grpc.generated.EvitaServiceGrpc$EvitaServiceBlockingStub.createReadOnlySession(EvitaServiceGrpc.java:685) ~[evita_external_api_grpc_shared-0.6-SNAPSHOT.jar:?]
	at io.evitadb.driver.EvitaClient.lambda$createSession$6(EvitaClient.java:250) ~[evita_java_driver-0.6-SNAPSHOT.jar:?]
	at io.evitadb.driver.EvitaClient.executeWithEvitaService(EvitaClient.java:148) ~[evita_java_driver-0.6-SNAPSHOT.jar:?]
	at io.evitadb.driver.EvitaClient.createSession(EvitaClient.java:249) ~[evita_java_driver-0.6-SNAPSHOT.jar:?]
	at io.evitadb.driver.EvitaClient.queryCatalog(EvitaClient.java:375) ~[evita_java_driver-0.6-SNAPSHOT.jar:?]
```

**Comment by novoj** [comment]
Can you provide more context (what operation have you executed and with what input parameters)?

**Comment by novoj** [comment]
No details included and we made some enhancements historically. I'm closing this issue unless explicit scenario on current evitaDB version is provided (please reopen issue).
