### ISSUE TITLE
NPE when using attributeBetween for attributeHistogram

### ISSUE THREAD

**Issue by lukashornych** [FgForrest/evitaDB#401]
In demo dataset when `attributeHistogram` is requested with `attributeBetween` in a `userFilter`:
```
query(
  collection("Product"),
  filterBy(
    userFilter(
      attributeBetween("battery-capacity", "3000", "7000")
    )
  ),
  require(
    attributeHistogram(10, "battery-capacity")
  )
)
```
evitaDB returns NPE:
```
Caused by: java.lang.NullPointerException: null
	at java.base/java.util.Comparator.lambda$comparingLong$6043328a$1(Comparator.java:515)
	at java.base/java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.base/java.util.TimSort.sort(TimSort.java:220)
	at java.base/java.util.Arrays.sort(Arrays.java:1307)
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:353)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at evita.engine@10.1-SNAPSHOT/io.evitadb.core.query.algebra.base.AndFormula.lambda$getRoaringBitmaps$10(AndFormula.java:237)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at evita.engine@10.1-SNAPSHOT/io.evitadb.core.query.algebra.base.AndFormula.getRoaringBitmaps(AndFormula.java:233)
	at evita.engine@10.1-SNAPSHOT/io.evitadb.core.query.algebra.base.AndFormula.computeInternal(AndFormula.java:211)
	at evita.engine@10.1-SNAPSHOT/io.evitadb.core.query.algebra.AbstractCacheableFormula.compute(AbstractCacheableFormula.java:62)
	at evita.engine@10.1-SNAPSHOT/io.evitadb.core.query.extraResult.translator.histogram.producer.AttributeHistogramProducer.hasSenseWithMandatoryFilter(AttributeHistogramProducer.java:439)
	at evita.engine@10.1-SNAPSHOT/io.evitadb.core.query.extraResult.translator.histogram.producer.AttributeHistogramProducer.lambda$fabricate$5(AttributeHistogramProducer.java:368)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1850)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at evita.engine@10.1-SNAPSHOT/io.evitadb.core.query.extraResult.translator.histogram.producer.AttributeHistogramProducer.fabricate(AttributeHistogramProducer.java:391)
	at evita.engine@10.1-SNAPSHOT/io.evitadb.core.query.QueryPlan.fabricateExtraResults(QueryPlan.java:228)
	at evita.engine@10.1-SNAPSHOT/io.evitadb.core.query.QueryPlan.execute(QueryPlan.java:200)
	at evita.engine@10.1-SNAPSHOT/io.evitadb.core.EntityCollection.getEntities(EntityCollection.java:333)
	at evita.engine@10.1-SNAPSHOT/io.evitadb.core.EvitaSession.query(EvitaSession.java:1073)
	at evita.engine@10.1-SNAPSHOT/io.evitadb.core.EvitaSession.query(EvitaSession.java:439)
	... 24 common frames omitted
```
Only if price constraints needed for `priceForSale` calculation (even though `priceForSale` isn't needed by user) are used as well, evitaDB doesn't throw any error, like so:
```
query(
  collection("Product"),
  filterBy(
    priceInCurrency("EUR"),
    priceInPriceLists("basic"),
    userFilter(
      attributeBetween("battery-capacity", "3000", "7000")
    )
  ),
  require(
    attributeHistogram(10, "battery-capacity")
  )
)
```

**Comment by novoj** [comment]
The problem was caused by the fact, that there was single filtering constraint targetting the same attribute as requested in histogram which caused that the entire filtering constraint was eliminated when calculating the histogram:

1. the filtering constraint excluding user filter was NULL
2. the filtering constraint including user filter, but excluding the constraint targeting the attribute for which the histogram is computed

These two places were places where the NPE occured. I updated the expectations, wrote the test and made it work.
