### ISSUE TITLE
Problem with deleting catalogs on Windows OS

### ISSUE THREAD

**Issue by Khertys** [FgForrest/evitaDB#79]
When running evita tests on Windows, the used catalog cannot be deleted. Perhaps some IO handler on server side is prohibiting the delete operation.

```
Mar 29, 2023 10:51:27 AM io.grpc.internal.SerializingExecutor run
SEVERE: Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@4fe29d07
io.evitadb.exception.UnexpectedIOException: Failed to delete file: .\data\catalogs\testingCatalog\testingCatalog.catalog
	at evita.common@0.5-SNAPSHOT/io.evitadb.utils.FileUtils.lambda$deleteDirectory$1(FileUtils.java:80)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at evita.common@0.5-SNAPSHOT/io.evitadb.utils.FileUtils.deleteDirectory(FileUtils.java:75)
	at evita.store.server/io.evitadb.store.catalog.DefaultCatalogPersistenceService.delete(DefaultCatalogPersistenceService.java:364)
	at evita.engine/io.evitadb.core.Catalog.delete(Catalog.java:498)
	at evita.engine/io.evitadb.core.Evita.removeCatalogInternal(Evita.java:566)
	at evita.engine/io.evitadb.core.Evita.update(Evita.java:340)
	at evita.engine/io.evitadb.core.Evita.deleteCatalogIfExists(Evita.java:310)
	at evita.external.api.grpc/io.evitadb.externalApi.grpc.services.EvitaService.deleteCatalogIfExists(EvitaService.java:176)
	at evita.external.api.grpc.shared/io.evitadb.externalApi.grpc.generated.EvitaServiceGrpc$MethodHandlers.invoke(EvitaServiceGrpc.java:733)
	at grpc.workaround.build@0.5-SNAPSHOT/io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
	at grpc.workaround.build@0.5-SNAPSHOT/io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at grpc.workaround.build@0.5-SNAPSHOT/io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at grpc.workaround.build@0.5-SNAPSHOT/io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at evita.external.api.grpc/io.evitadb.externalApi.grpc.services.interceptors.GlobalExceptionHandlerInterceptor$ExceptionHandler.onHalfClose(GlobalExceptionHandlerInterceptor.java:72)
	at grpc.workaround.build@0.5-SNAPSHOT/io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:355)
	at grpc.workaround.build@0.5-SNAPSHOT/io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:867)
	at grpc.workaround.build@0.5-SNAPSHOT/io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at grpc.workaround.build@0.5-SNAPSHOT/io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at jboss.threads@3.5.0.Final/org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at jboss.threads@3.5.0.Final/org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at jboss.threads@3.5.0.Final/org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by novoj** [comment]
Let me first describe the logic and the crucial points for this problem. I currently have no Windows environment to manually debug the problem, so I'd like to ask you for cooperation.

- the streams are opened in classes `WriteOnlyFileHandle` and `ReadOnlyFileHandle` and these are only used in `MemTable`
- I checked the logic of `MemTable#close` method and it seems, that the handles are properly closed there
- next step are the places where the `MemTable` is held and these are:
   - `DefaultCatalogPersistenceService` -> `Catalog`
   - `DefaultEntityCollectionPersistenceService` -> `EntityCollection`
- I checked the logic of these services and in `close` method, they correctly close `MemTable` close
- then there are `terminate` methods in `Catalog` and `EntityCollection` that should be called at the Evita disposal and call the close methods of persistence services
- terminate method in `EntityCollection` seems ok
- terminate method in `Catalog` didn't close `ioService` and that might have been the problem

The `terminate` method was altered by commit in this issue (and fix pushed directly to `dev` branch, since it's obvious bug). Can you please retest the problem and check whether this was the cause or should I look further?!

**Comment by novoj** [comment]
I tried https://github.com/jenkinsci/lib-file-leak-detector and did some fixes in tests. Also added cleaning function to `CleaningTestExecutorListener` and finally found out that when the catalog is deleted it's not terminated before.

Can you please test it once more?

**Comment by Khertys** [comment]
This last commit fixed it! Thank you
